version: '3.0'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH='~/app'
      - DB_HOST=172.20.0.3
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=app
      - REDIS_HOST=172.20.0.4
      - REDIS_PORT=6379
    networks:
      app_network:
        ipv4_address: 172.20.0.2

  postgres:
    image: postgres:15.3-alpine
    container_name: psql_app
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      app_network:
        ipv4_address: 172.20.0.3

  redis:
    image: redis:latest
    container_name: redis_app
    restart: always
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PORT=6379
    networks:
      app_network:
        ipv4_address: 172.20.0.4

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_volume:
  redis_data: